### PR TITLE
Adding @vachashah @dblock @harshavamsi to maintainers list

### PR DESCRIPTION
**Pull request by harshavamsi**
Signed-off-by: Harsha Vamsi Kalluri <harshavamsi096@gmail.com>

### Description
- Updates maintainers file to reflect current maintainers.
- Updates admin file to link to meta repository
- Updates to codeowners to reflect current code owners

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Rebase?

**Comment by harshavamsi** [comment]
> Rebase?

Rebased.

**Comment by dblock** [comment]
And now it needs a CHANGELOG entry! ;)

**Comment by harshavamsi** [comment]
> And now it needs a CHANGELOG entry! ;)

Just added!

**Review by VachaShah — APPROVED** [review]

**Comment by wbeckler** [comment]
@dblock Can you approve this? While we are deprecating this client, we still need maintainers to handle CVEs, for example.

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
CI is failing, someone should please look at this @wbeckler

**Comment by Yury-Fridlyand** [comment]
CI was fixed in #92. Do you want to rebase?

**Pull request merged**
